INSERT INTO
    `subcategory`
VALUES
    (
        1,
        'Men\'s Fashion',
        1,
        'https://shepreneurhub.blob.core.windows.net/shepreneurhub/1.webp'
    ),
    (
        2,
        'Women\'s Fashion',
        1,
        'https://shepreneurhub.blob.core.windows.net/shepreneurhub/2.webp'
    ),
    (
        3,
        'Custom Suits',
        2,
        'https://shepreneurhub.blob.core.windows.net/shepreneurhub/3.webp'
    ),
    (4, 'Alterations', 2,  'https://shepreneurhub.blob.core.windows.net/shepreneurhub/4.webp'),
    (5, 'Jewelry', 3,  'https://shepreneurhub.blob.core.windows.net/shepreneurhub/5.webp'),
    (6, 'Handbags', 3,  'https://shepreneurhub.blob.core.windows.net/shepreneurhub/6.webp'),
    (7, 'Facial Treatments', 4,  'https://shepreneurhub.blob.core.windows.net/shepreneurhub/7.webp'),
    (8, 'Body Care', 4,  'https://shepreneurhub.blob.core.windows.net/shepreneurhub/8.webp'),
    (9, 'Bridal Makeup', 5, 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/9.jpeg'),
    (10, 'Makeup for Photography', 5, 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/10.webp'),
    (11, 'Painting', 6,  'https://shepreneurhub.blob.core.windows.net/shepreneurhub/11.jpeg'),
    (12, 'Sculpture', 6,  'https://shepreneurhub.blob.core.windows.net/shepreneurhub/12.webp'),
    (13, 'Wedding Venue Decorations', 7,  'https://shepreneurhub.blob.core.windows.net/shepreneurhub/13.jpeg'),
    (14, 'Catering', 7,  'https://shepreneurhub.blob.core.windows.net/shepreneurhub/14.jpeg'),
    (15, 'Interior Design', 8,  'https://shepreneurhub.blob.core.windows.net/shepreneurhub/15.webp'),
    (16, 'Gardening', 8,  'https://shepreneurhub.blob.core.windows.net/shepreneurhub/16.jpeg'),
    (17, 'Therapy', 9, 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/17.webp'),
    (18, 'Consulting', 9, 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/18.webp'),
    (19, 'Corporate Events', 10, 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/19.jpg'),
    (20, 'Weddings', 10, 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/20.jpg'),
    (21, 'Infant clothes', 11,  'https://shepreneurhub.blob.core.windows.net/shepreneurhub/21.webp'),
    (22, 'Infant products', 11,  'https://shepreneurhub.blob.core.windows.net/shepreneurhub/22.webp'),
    (23, 'Pet Food', 12,  'https://shepreneurhub.blob.core.windows.net/shepreneurhub/23.webp'),
    (24, 'Pet Toys', 12,  'https://shepreneurhub.blob.core.windows.net/shepreneurhub/24.webp'),
    (25, 'Cakes', 13,  'https://shepreneurhub.blob.core.windows.net/shepreneurhub/25.webp'),
    (26, 'Cookies', 13,  'https://shepreneurhub.blob.core.windows.net/shepreneurhub/26.jpeg');


    INSERT INTO `company` (`name`, `address`, `hours`, `phone`, `gmail`, `image`, `catid`, `subcatid`) VALUES 
('Company A1', '456 Elm St, City, Country', '10 AM - 6 PM', '234-567-8901', 'companyA1@example.com', 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/company_image.png', 1, 1),
('Company A2', '457 Elm St, City, Country', '10 AM - 6 PM', '234-567-8902', 'companyA2@example.com', 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/company_image.png', 1, 1),
('Company A3', '458 Elm St, City, Country', '10 AM - 6 PM', '234-567-8903', 'companyA3@example.com', 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/company_image.png', 1, 2),
('Company A4', '459 Elm St, City, Country', '10 AM - 6 PM', '234-567-8904', 'companyA4@example.com', 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/company_image.png', 1, 2),
('Company B1', '789 Oak St, City, Country', '8 AM - 4 PM', '345-678-9012', 'companyB1@example.com', 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/company_image.png', 2, 3),
('Company B2', '790 Oak St, City, Country', '8 AM - 4 PM', '345-678-9013', 'companyB2@example.com', 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/company_image.png', 2, 3),
('Company B3', '791 Oak St, City, Country', '8 AM - 4 PM', '345-678-9014', 'companyB3@example.com', 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/company_image.png', 2, 4),
('Company B4', '792 Oak St, City, Country', '8 AM - 4 PM', '345-678-9015', 'companyB4@example.com', 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/company_image.png', 2, 4),
('Company C1', '321 Pine St, City, Country', '7 AM - 3 PM', '456-789-0123', 'companyC1@example.com', 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/company_image.png', 3, 5),
('Company C2', '322 Pine St, City, Country', '7 AM - 3 PM', '456-789-0124', 'companyC2@example.com', 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/company_image.png', 3, 5),
('Company C3', '323 Pine St, City, Country', '7 AM - 3 PM', '456-789-0125', 'companyC3@example.com', 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/company_image.png', 3, 6),
('Company C4', '324 Pine St, City, Country', '7 AM - 3 PM', '456-789-0126', 'companyC4@example.com', 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/company_image.png', 3, 6),
('Company D1', '123 Main St, City, Country', '9 AM - 5 PM', '123-456-7890', 'companyD1@gmail.com', 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/company_image.png', 4, 7),
('Company D2', '124 Main St, City, Country', '9 AM - 5 PM', '123-456-7891', 'companyD2@gmail.com', 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/company_image.png', 4, 7),
('Company D3', '125 Main St, City, Country', '9 AM - 5 PM', '123-456-7892', 'companyD3@gmail.com', 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/company_image.png', 4, 8),
('Company D4', '126 Main St, City, Country', '9 AM - 5 PM', '123-456-7893', 'companyD4@gmail.com', 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/company_image.png', 4, 8),
('Company E1', '654 Maple St, City, Country', '11 AM - 7 PM', '567-890-1234', 'companyE1@example.com', 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/company_image.png', 5, 9),
('Company E2', '655 Maple St, City, Country', '11 AM - 7 PM', '567-890-1235', 'companyE2@example.com', 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/company_image.png', 5, 9),
('Company E3', '656 Maple St, City, Country', '11 AM - 7 PM', '567-890-1236', 'companyE3@example.com', 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/company_image.png', 5, 10),
('Company E4', '657 Maple St, City, Country', '11 AM - 7 PM', '567-890-1237', 'companyE4@example.com', 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/company_image.png', 5, 10),
('Company F1', '246 Cedar St, City, Country', '9 AM - 5 PM', '678-901-2345', 'companyF1@example.com', 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/company_image.png', 6, 11),
('Company F2', '247 Cedar St, City, Country', '9 AM - 5 PM', '678-901-2346', 'companyF2@example.com', 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/company_image.png', 6, 11),
('Company F3', '248 Cedar St, City, Country', '9 AM - 5 PM', '678-901-2347', 'companyF3@example.com', 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/company_image.png', 6, 12),
('Company F4', '249 Cedar St, City, Country', '9 AM - 5 PM', '678-901-2348', 'companyF4@example.com', 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/company_image.png', 6, 12),
('Company G1', '357 Elm St, City, Country', '10 AM - 6 PM', '789-012-3456', 'companyG1@example.com', 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/company_image.png', 7, 13),
('Company G2', '358 Elm St, City, Country', '10 AM - 6 PM', '789-012-3457', 'companyG2@example.com', 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/company_image.png', 7, 13),
('Company G3', '359 Elm St, City, Country', '10 AM - 6 PM', '789-012-3458', 'companyG3@example.com', 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/company_image.png', 7, 14),
('Company G4', '360 Elm St, City, Country', '10 AM - 6 PM', '789-012-3459', 'companyG4@example.com', 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/company_image.png', 7, 14),
('Company H1', '468 Oak St, City, Country', '8 AM - 4 PM', '890-123-4567', 'companyH1@example.com', 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/company_image.png', 8, 15),
('Company H2', '469 Oak St, City, Country', '8 AM - 4 PM', '890-123-4568', 'companyH2@example.com', 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/company_image.png', 8, 15),
('Company H3', '470 Oak St, City, Country', '8 AM - 4 PM', '890-123-4569', 'companyH3@example.com', 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/company_image.png', 8, 16),
('Company H4', '471 Oak St, City, Country', '8 AM - 4 PM', '890-123-4570', 'companyH4@example.com', 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/company_image.png', 8, 16),
('Company I1', '579 Pine St, City, Country', '7 AM - 3 PM', '901-234-5678', 'companyI1@example.com', 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/company_image.png', 9, 17),
('Company I2', '580 Pine St, City, Country', '7 AM - 3 PM', '901-234-5679', 'companyI2@example.com', 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/company_image.png', 9, 17),
('Company I3', '581 Pine St, City, Country', '7 AM - 3 PM', '901-234-5680', 'companyI3@example.com', 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/company_image.png', 9, 18),
('Company I4', '582 Pine St, City, Country', '7 AM - 3 PM', '901-234-5681', 'companyI4@example.com', 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/company_image.png', 9, 18),
('Company J1', '680 Maple St, City, Country', '11 AM - 7 PM', '012-345-6789', 'companyJ1@example.com', 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/company_image.png', 10, 19),
('Company J2', '681 Maple St, City, Country', '11 AM - 7 PM', '012-345-6790', 'companyJ2@example.com', 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/company_image.png', 10, 19),
('Company J3', '682 Maple St, City, Country', '11 AM - 7 PM', '012-345-6791', 'companyJ3@example.com', 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/company_image.png', 10, 20),
('Company J4', '683 Maple St, City, Country', '11 AM - 7 PM', '012-345-6792', 'companyJ4@example.com', 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/company_image.png', 10, 20),
('Company K1', '789 Cedar St, City, Country', '10 AM - 4 PM', '123-456-7890', 'companyK1@example.com', 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/company_image.png', 11, 21),
('Company K2', '790 Cedar St, City, Country', '10 AM - 4 PM', '123-456-7891', 'companyK2@example.com', 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/company_image.png', 11, 21),
('Company K3', '791 Cedar St, City, Country', '10 AM - 4 PM', '123-456-7892', 'companyK3@example.com', 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/company_image.png', 11, 22),
('Company K4', '792 Cedar St, City, Country', '10 AM - 4 PM', '123-456-7893', 'companyK4@example.com', 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/company_image.png', 11, 22),
('Company L1', '987 Fir St, City, Country', '7 AM - 3 PM', '234-567-8901', 'companyL1@example.com', 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/company_image.png', 12, 23),
('Company L2', '988 Fir St, City, Country', '7 AM - 3 PM', '234-567-8902', 'companyL2@example.com', 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/company_image.png', 12, 23),
('Company L3', '989 Fir St, City, Country', '7 AM - 3 PM', '234-567-8903', 'companyL3@example.com', 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/company_image.png', 12, 24),
('Company L4', '990 Fir St, City, Country', '7 AM - 3 PM', '234-567-8904', 'companyL4@example.com', 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/company_image.png', 12, 24),
('Company M1', '135 Willow St, City, Country', '11 AM - 7 PM', '345-678-9012', 'companyM1@example.com', 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/company_image.png', 13, 25),
('Company M2', '136 Willow St, City, Country', '11 AM - 7 PM', '345-678-9013', 'companyM2@example.com', 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/company_image.png', 13, 25),
('Company M3', '137 Willow St, City, Country', '11 AM - 7 PM', '345-678-9014', 'companyM3@example.com', 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/company_image.png', 13, 26),
('Company M4', '138 Willow St, City, Country', '11 AM - 7 PM', '345-678-9015', 'companyM4@example.com', 'https://shepreneurhub.blob.core.windows.net/shepreneurhub/company_image.png', 13, 26);